### ISSUE TITLE
ImportError: cannot import name 'bilateral_blur' from 'kornia.filters' on comfy plugin for webui

### ISSUE THREAD

**Issue by f-rank** [bvhari/ComfyUI_ImageProcessing#1]
On ComfyUI, all works as expected.
Using the comfy plugin for auto1111 to apply the image processing plugins after generating, on startup I get this thrown to console:

[ComfyUI] Traceback (most recent call last):
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1698, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ImageProcessing\__init__.py", line 1, in <module>
    from .imageprocessing import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ImageProcessing\imageprocessing.py", line 2, in <module>
    from kornia.filters import bilateral_blur, unsharp_mask
ImportError: cannot import name 'bilateral_blur' from 'kornia.filters' (d:\WORK\conda_envs\automatic\stable-diffusion-webui\venv\lib\site-packages\kornia\filters\__init__.py)

[ComfyUI] Cannot import D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ImageProcessing module for custom nodes: cannot import name 'bilateral_blur' from 'kornia.filters' (d:\WORK\conda_envs\automatic\stable-diffusion-webui\venv\lib\site-packages\kornia\filters\__init__.py)

Is there someway to avoid this so it loads, maybe it is some recursion going on, or namespace problem.
Unfortunately I am not fluent enough in Python to patch it.
Anyway, thanks for the brilliant plugin.

**Comment by bvhari** [comment]
Hi,
Is the issue still present?
Activating the A1111 venv and manually updating kornia with "pip install --upgrade kornia" might help

**Comment by Essoje** [comment]
For posterity's sake, `pip install --upgrade kornia` did solve this for me.

**Comment by bvhari** [comment]
Closing this issue as it is stale.
